service: promodeAgro-ecommerce-api

frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  region: ap-south-1
  runtime: nodejs18.x
  role: arn:aws:iam::851725323791:role/ecommerce_Lambda_Role
  versionFunctions: false
  timeout: 29
  logs:
      httpApi: true
  httpApi:
   
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizer
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

custom:
  warmup:
    default:
      enabled: true
      events:
        - schedule: rate(5 minutes)
  # customDomain:
  #   domainName: api.b2c.promodeagro.com
  #   basePath: project1
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

  serverless-offline:
    httpPort: 4000

functions:
  - ${file(products/function.yml)}

  # - ${file(RBAC/function.yml)}
  # - ${file(loginwithotp/function.yml)}

  - ${file(OrderBills/function.yml)}
  - ${file(Users/function.yml)}
  - ${file(inventory/function.yml)}
  # - ${file(Login/function.yml)}
  # - ${file(Customer/function.yml)}
  - ${file(order/function.yml)}
  - ${file(payment/function.yml)}
  - ${file(stepFunctions/function.yml)}
  - ${file(cart/function.yml)}
  - ${file(category/function.yml)}
  - ${file(deliverySlots/function.yml)}
  - ${file(offers/function.yml)}
  - ${file(reviews/function.yml)}
  - ${file(wishlist/function.yml)}
  - ${file(sales/function.yml)}
  - ${file(saveForLater/function.yml)}
  - ${file(payment/function.yml)}
  - ${file(userSession/function.yml)}

  
  # - ${file(webhooks/function.yml)}
plugins:
  - serverless-plugin-warmup

  # - serverless-domain-manager

  - serverless-offline
#   - serverless-esbuild

# custom:
#   esbuild:
#     bundle: true
#     minify: false
#     sourcemap: true
#     exclude: []
#     format: 'cjs'  # This is crucial for ESM support
#     concurrency: 10
#     zipConcurrency: 10
#     define:
#       'require.resolve': undefined
#     platform: 'node'
#     external:
#       - 'aws-sdk'
    
# package:
#   individually: true

# useDotenv: true

